### ISSUE TITLE
[Question] Correct way to add SonarQube Server 8.0 support

### ISSUE THREAD

**Issue by innokentiyt** [usaa/sonar-quality-gates#3]
Hi!

This plugin is very useful for me, but I use SonarQube Server 8.0, which is not supported by the plugin. I experimented with code and implemented initial support for 8.0 API. So far it's working good for me.

And I have a question. What will be the correct way to publish this modifications? Publish them in cloned repository? Recreate repository with a new name, e. g. sonar-quality-gates-v2?

**Comment by geofflancaster** [comment]
Create an issue for v8.+ support and then submit a PR against the issue.

Thanks!
